/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as IndexRouteImport } from './app/index'
import { Route as MainRouteImport } from './app/_main'
import { Route as OnboardingRouteImport } from './app/onboarding'
import { Route as MainDetailRouteImport } from './app/_main/detail'
import { Route as MainMarketplaceRouteImport } from './app/_main/marketplace'
import { Route as MainProfileRouteImport } from './app/_main/profile'
import { Route as MainSnapRouteImport } from './app/_main/snap'
import { Route as MainTrendingRouteImport } from './app/_main/trending'
import { Route as ApiSplatRouteImport } from './app/api/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MainDetailRoute = MainDetailRouteImport.update({
  id: '/detail',
  path: '/detail',
  getParentRoute: () => MainRoute,
} as any)
const MainMarketplaceRoute = MainMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => MainRoute,
} as any)
const MainProfileRoute = MainProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MainRoute,
} as any)
const MainSnapRoute = MainSnapRouteImport.update({
  id: '/snap',
  path: '/snap',
  getParentRoute: () => MainRoute,
} as any)
const MainTrendingRoute = MainTrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => MainRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/detail': typeof MainDetailRoute
  '/marketplace': typeof MainMarketplaceRoute
  '/profile': typeof MainProfileRoute
  '/snap': typeof MainSnapRoute
  '/trending': typeof MainTrendingRoute
  '/api/$': typeof ApiSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/detail': typeof MainDetailRoute
  '/marketplace': typeof MainMarketplaceRoute
  '/profile': typeof MainProfileRoute
  '/snap': typeof MainSnapRoute
  '/trending': typeof MainTrendingRoute
  '/api/$': typeof ApiSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_main': typeof MainRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_main/detail': typeof MainDetailRoute
  '/_main/marketplace': typeof MainMarketplaceRoute
  '/_main/profile': typeof MainProfileRoute
  '/_main/snap': typeof MainSnapRoute
  '/_main/trending': typeof MainTrendingRoute
  '/api/$': typeof ApiSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/detail'
    | '/marketplace'
    | '/profile'
    | '/snap'
    | '/trending'
    | '/api/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/detail'
    | '/marketplace'
    | '/profile'
    | '/snap'
    | '/trending'
    | '/api/$'
  id:
    | '__root__'
    | '/'
    | '/_main'
    | '/onboarding'
    | '/_main/detail'
    | '/_main/marketplace'
    | '/_main/profile'
    | '/_main/snap'
    | '/_main/trending'
    | '/api/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MainRoute: typeof MainRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/detail': {
      id: '/_main/detail'
      path: '/detail'
      fullPath: '/detail'
      preLoaderRoute: typeof MainDetailRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/marketplace': {
      id: '/_main/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MainMarketplaceRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/profile': {
      id: '/_main/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof MainProfileRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/snap': {
      id: '/_main/snap'
      path: '/snap'
      fullPath: '/snap'
      preLoaderRoute: typeof MainSnapRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/trending': {
      id: '/_main/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof MainTrendingRouteImport
      parentRoute: typeof MainRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MainRouteChildren {
  MainDetailRoute: typeof MainDetailRoute
  MainMarketplaceRoute: typeof MainMarketplaceRoute
  MainProfileRoute: typeof MainProfileRoute
  MainSnapRoute: typeof MainSnapRoute
  MainTrendingRoute: typeof MainTrendingRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainDetailRoute: MainDetailRoute,
  MainMarketplaceRoute: MainMarketplaceRoute,
  MainProfileRoute: MainProfileRoute,
  MainSnapRoute: MainSnapRoute,
  MainTrendingRoute: MainTrendingRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MainRoute: MainRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
